const express=require('express');const session=require('express-session');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');const path=require('path');const fs=require('fs');
const app=express();const dataDir=path.join(__dirname,'data');fs.mkdirSync(dataDir,{recursive:true});const db=new Database(path.join(dataDir,'store.db'));app.use(express.urlencoded({extended:true}));app.use(express.json());app.use(express.static(path.join(__dirname,'public')));app.use(session({secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,maxAge:86400000}}));app.set('view engine','ejs');app.set('views',path.join(__dirname,'views'));
db.exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT,price INTEGER NOT NULL,duration TEXT,description TEXT,active INTEGER DEFAULT 1,featured INTEGER DEFAULT 0);CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_no TEXT UNIQUE NOT NULL,product_id INTEGER NOT NULL,customer_name TEXT,customer_contact TEXT,payment_method TEXT,status TEXT DEFAULT 'PENDING',created_at TEXT DEFAULT CURRENT_TIMESTAMP,notes TEXT,FOREIGN KEY(product_id) REFERENCES products(id));CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT DEFAULT 'staff',active INTEGER DEFAULT 1);CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),message TEXT NOT NULL,status TEXT DEFAULT 'PENDING',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare('SELECT 1 FROM admins LIMIT 1').get()) db.prepare('INSERT INTO admins(username,password,role) VALUES(?,?,?)').run('admin',bcrypt.hashSync(process.env.ADMIN_PASSWORD||'admin123',10),'owner');
if(!db.prepare('SELECT 1 FROM products LIMIT 1').get()){const p=[['Netflix 4K','Netflix',129,'1 Month'],['Netflix 4K (Private Profile)','Netflix',199,''],['Prime Video 1 Device Plan','Prime Video',199,'6 Months'],['Prime Video on Your Mail','Prime Video',299,'6 Months'],['Sun NXT on Your Number Activation','Sun NXT',349,'1 Year'],['YouTube Premium','YouTube',59,'1 Month'],['Crunchyroll','Crunchyroll',199,'1 Year'],['Spotify','Spotify',99,'3 Months'],['YouTube + Spotify Combo','Combo',199,'3 Months'],['YouTube + Prime','Combo',99,''],['Netflix + Prime','Combo',159,''],['Hoichoi on Your Number Activation','Hoichoi',399,'1 Year']];const s=db.prepare('INSERT INTO products(name,category,price,duration) VALUES(?,?,?,?)');const tx=db.transaction(()=>p.forEach(x=>s.run(...x)));tx();}
function auth(req,res,next){if(!req.session.admin)return res.redirect('/admin/login');next()}function owner(req,res,next){if(req.session.admin?.role!=='owner')return res.status(403).send('Owner access required');next()}function orderNo(){return 'ORD-'+Date.now().toString(36).toUpperCase()+'-'+Math.floor(100+Math.random()*900)}
app.get('/',(req,res)=>res.render('index',{products:db.prepare('SELECT * FROM products WHERE active=1 ORDER BY featured DESC,id').all(),reviews:db.prepare("SELECT * FROM reviews WHERE status='APPROVED' ORDER BY id DESC LIMIT 12").all()}));
app.get('/product/:id',(req,res)=>{const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(req.params.id);if(!p)return res.status(404).send('Product not found');res.render('product',{p})});
app.post('/api/reviews',(req,res)=>{const {name,rating,message}=req.body;const r=Number(rating);if(!name||!message||r<1||r>5)return res.status(400).json({error:'Please enter your name, rating and review.'});db.prepare('INSERT INTO reviews(name,rating,message) VALUES(?,?,?)').run(String(name).trim().slice(0,80),r,String(message).trim().slice(0,500));res.json({ok:true,message:'Thanks! Your review was submitted for approval.'})});
app.post('/api/orders',(req,res)=>{const {product_id,customer_name,customer_contact,payment_method,notes}=req.body;const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(product_id);if(!p)return res.status(400).json({error:'Product unavailable'});const no=orderNo();db.prepare('INSERT INTO orders(order_no,product_id,customer_name,customer_contact,payment_method,notes) VALUES(?,?,?,?,?,?)').run(no,p.id,customer_name||'',customer_contact||'',payment_method||'UPI',notes||'');res.json({ok:true,order_no:no})});
app.get('/order/:no',(req,res)=>{const o=db.prepare('SELECT orders.*,products.name product_name,products.price FROM orders JOIN products ON products.id=orders.product_id WHERE order_no=?').get(req.params.no);if(!o)return res.status(404).send('Order not found');res.render('order',{o})});
app.get('/admin/login',(req,res)=>res.render('login',{error:null}));app.post('/admin/login',(req,res)=>{const a=db.prepare('SELECT * FROM admins WHERE username=? AND active=1').get(req.body.username);if(!a||!bcrypt.compareSync(req.body.password,a.password))return res.render('login',{error:'Invalid login'});req.session.admin={id:a.id,username:a.username,role:a.role};res.redirect('/admin')});app.get('/admin/logout',(req,res)=>req.session.destroy(()=>res.redirect('/admin/login')));
app.post('/admin/reviews/status',auth,(req,res)=>{db.prepare('UPDATE reviews SET status=? WHERE id=?').run(req.body.status,req.body.id);res.redirect('/admin')});app.post('/admin/reviews/delete',owner,(req,res)=>{db.prepare('DELETE FROM reviews WHERE id=?').run(req.body.id);res.redirect('/admin')});
app.get('/admin',auth,(req,res)=>{const stats={products:db.prepare('SELECT COUNT(*) n FROM products').get().n,orders:db.prepare('SELECT COUNT(*) n FROM orders').get().n,pending:db.prepare("SELECT COUNT(*) n FROM orders WHERE status='PENDING'").get().n,revenue:db.prepare("SELECT COALESCE(SUM(products.price),0) n FROM orders JOIN products ON products.id=orders.product_id WHERE orders.status='PAID'").get().n};res.render('dashboard',{admin:req.session.admin,stats,orders:db.prepare('SELECT orders.*,products.name product_name,products.price FROM orders JOIN products ON products.id=orders.product_id ORDER BY orders.id DESC LIMIT 20').all(),reviews:db.prepare('SELECT * FROM reviews ORDER BY id DESC LIMIT 30').all()})});
app.get('/admin/products',auth,(req,res)=>res.render('products',{admin:req.session.admin,products:db.prepare('SELECT * FROM products ORDER BY id DESC').all()}));
app.post('/admin/products/save',auth,(req,res)=>{const {id,name,category,price,duration,description,active,featured}=req.body;if(id)db.prepare('UPDATE products SET name=?,category=?,price=?,duration=?,description=?,active=?,featured=? WHERE id=?').run(name,category,Number(price),duration,description||'',active?1:0,featured?1:0,id);else db.prepare('INSERT INTO products(name,category,price,duration,description,active,featured) VALUES(?,?,?,?,?,?,?)').run(name,category,Number(price),duration,description||'',active?1:0,featured?1:0);res.redirect('/admin/products')});
app.post('/admin/products/delete',owner,(req,res)=>{db.prepare('DELETE FROM products WHERE id=?').run(req.body.id);res.redirect('/admin/products')});
app.post('/admin/orders/status',auth,(req,res)=>{db.prepare('UPDATE orders SET status=? WHERE id=?').run(req.body.status,req.body.id);res.redirect('/admin')});
app.get('/admin/staff',owner,(req,res)=>res.render('staff',{admin:req.session.admin,staff:db.prepare('SELECT id,username,role,active FROM admins ORDER BY id').all()}));
app.post('/admin/staff/save',owner,(req,res)=>{const {username,password,role}=req.body;if(password)db.prepare('INSERT INTO admins(username,password,role) VALUES(?,?,?)').run(username,bcrypt.hashSync(password,10),role||'staff');res.redirect('/admin/staff')});app.post('/admin/staff/delete',owner,(req,res)=>{if(Number(req.body.id)!==req.session.admin.id)db.prepare('DELETE FROM admins WHERE id=?').run(req.body.id);res.redirect('/admin/staff')});
const PORT=process.env.PORT||3000;app.listen(PORT,()=>console.log('Store running on '+PORT));
